name: Login System

on:
  schedule:
    - cron: "00 0,12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    
      - name: Gettings files from Repo
        uses: actions/checkout@v4
        
      - name: Install Requeriments
        run: |
          pip install -r requirements.txt

      - name: Execute main script 1
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
          DEVICE_INFO_SECRET: ${{ secrets.DEVICE_INFO_SECRET }}
          APP_CHECK_SECRET: ${{ secrets.APP_CHECK_SECRET }}
          USER_AGENT_SECRET_2: ${{ secrets.USER_AGENT_SECRET_2 }}
          webhookEnable: ${{ secrets.WEBHOOK_ENABLE }}
      - name: Keep-alive (60 days issue)
        run: |
          # 最後にコミットされた日付を取得
          LAST_COMMIT_DATE=$(git log -1 --format=%ct)
          CURRENT_DATE=$(date +%s)
          # 50日（4320000秒）経過しているかチェック
          if [ $((CURRENT_DATE - LAST_COMMIT_DATE)) -gt 4320000 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit --allow-empty -m "keep-alive: 60 days prevention"
            git push
          else
            echo "Skipping keep-alive commit (less than 50 days since last activity)."
          fi


